# ==========================================
# KONFIGURASI UTAMA SUHAA.ID
# ==========================================
title: "Suhaa.id"
email: "anda@email.com"
description: >- # Deskripsi untuk Google
  Ruang refleksi pribadi tentang hukum, dinamika politik, 
  dan jurnal rasa sehari-hari.
author: "Suhaa"

# ==========================================
# PENGATURAN ALAMAT (JANGAN SALAH DISINI)
# ==========================================
url: "https://suhaa-id.github.io"
baseurl: "/suhaa99.github.io" 

# ==========================================
# TEKNIS
# ==========================================
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Format Link Tulisan (Tahun/Bulan/Judul)
collections:
  posts:
    permalink: /:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock

